name: CI
on:
  push:
      branches:
      - main
      - master
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - name: Build
        run: |
          sh -c "$(curl -fsSL https://git.io/JU2Im)"
      - name: Update
        run: |
          sh $HOME/update.sh
