name: CI
on:
  push:
      branches:
      - main
      - sync
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    timeout-minutes: 30

    steps:
      - name: Build
        run: curl -fsSL https://raw.githubusercontent.com/simaki/dotfiles/sync/install.sh | sh

      - name: Update
        run: sh $HOME/update.sh
